name: healthflow-website

static_sites:
- name: healthflow-frontend
  source_dir: /
  github:
    repo: HealthFlowEgy/healthflow-website
    branch: main
    deploy_on_push: true
  build_command: |
    npm install -g pnpm
    pnpm install
    pnpm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production

domains:
- domain: healthflow.tech
  type: PRIMARY
- domain: www.healthflow.tech
  type: ALIAS

