name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Build application
      run: pnpm run build

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: healthflow-website
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Update deployment status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Your website will be available at the DigitalOcean App Platform URL"
        echo "📋 Check the DigitalOcean dashboard for the live URL"

